### ISSUE TITLE
Radio buttons on iOS

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform-mobile#108]
This appears as a list, and when an option is selected, a check mark appears on the right hand side of the option. Is this right?

**Comment by dalezak** [comment]
Any thoughts on this @brandonrosage?

**Comment by dalezak** [comment]
@jshorland I believe this is an Ionic design convention, don't think we'll be able to change this  unless we use our own custom controls.

**Comment by dalezak** [comment]
Good news @jshorland!

Turns out in Ionic you can override styling to either iOS or Android, so in this case I can choose to use _Material Design_ which looks like this.

![simulator screen shot apr 21 2017 4 43 41 pm](https://cloud.githubusercontent.com/assets/91811/25298403/b1f756ee-26b1-11e7-8e4e-7f6955e66b94.png)
