### ISSUE TITLE
New Post Status is Always Draft, But Sometimes Shouldn't Be

### ISSUE THREAD

**Issue by dalezak** [ushahidi/platform-mobile#144]
Looks like if an `admin` submits a Post, it skips the `draft` status and goes right to being `published`.

**Comment by jshorland** [comment]
@dalezak looking at this again, it's not because i'm admin, it's actually because of a setting in the survey itself. "require posts be reviewed before publishing". If that's toggled "off" submitted posts, no matter who from, are published immediately. If on, they are kept in draft until a user with "manage posts" permissions publishes them. 
<img width="1407" alt="screen shot 2017-06-16 at 11 57 54 am" src="https://user-images.githubusercontent.com/3224856/27234469-379920b6-528b-11e7-9fef-043678619bf9.png">
